  // Define a list of inappropriate words or phrases
  const inappropriateWords = [
    'adult',
    'sensored',
    '2 girls 1 cup',
    'D쥐고',
    'D지고',
    'jonna',
    'jot같',
    'mi쳤',
    'tlqkf',
    'wlfkf',
    '같은 새끼',
    '같은새끼',
    '개 새끼',
    '개같',
    '개나대',
    '개넷',
    '개년',
    '개념빠가',
    '개련',
    '개련',
    '개부랄',
    '개새기',
    '개새끼',
    '개섹',
    '풀발',
    '씹선',
    '개소리',
    '개쓰래기',
    '개저씨',
    '거지같',
    '계새끼',
    '골 빈',
    '골1빈',
    '골빈',
    '괘새끼',
    '구1씹',
    '구씹',
    '그1켬',
    '그나물에',
    '그지 같',
    '그지같',
    '그켬',
    '극1혐',
    '극혐',
    '글러 먹',
    '글러먹',
    '기레기',
    '기자레기',
    '김치녀',
    '한녀',
    '된장녀',
    '앙기모띠',
    '소추',
    '퍄퍄',
    '눈나',
    '김여사',
    '보적보',
    '삼일한',
    '보슬아치',
    '보징어',
    '엑윽',
    '헤으응',
    '이기야',
    '노무',
    '부왘',
    '보픈카',
    '보라니',
    '상폐녀',
    '배빵',
    '누보햄',
    '찌질',
    '자박꼼',
    '로린 ',
    '펨베',
    '펨코',
    '허벌',
    '쿰.척',
    '쿰척',
    '까내리',
    '껒여',
    '꺼지세요',
    '꺼져요',
    '로 꺼져',
    '로꺼져',
    '로 꺼.져',
    '꺼.지',
    '꼬라지',
    '꼬라지',
    '꼴갑',
    '꼴값',
    '꼴깝',
    '꼴랑',
    '꼴보기',
    '꼴뵈기',
    '설거지론',
    '퐁퐁남',
    '퐁퐁녀',
    '나빼썅',
    '나쁜 새끼',
    '넌씨눈',
    '년놈',
    '노무노무',
    '노알라',
    '노친네',
    '느그',
    '느금',
    '뇌 텅',
    '뇌1텅',
    '뇌텅',
    '뇌피셜',
    '눈깔 파',
    '눈깔파',
    '눈새',
    '늬믜',
    '늬미',
    '니년',
    '니믜',
    '니미럴',
    '닝기리',
    'ㄷㅇㅂ',
    '다꺼져',
    '닥1',
    '닥2',
    '닥전',
    '닥쳐라',
    '닥치세',
    '닥후',
    '대가리',
    '대갈',
    '더럽네',
    '덜떨어',
    '덬',
    '도라이',
    '도랏',
    '도랐',
    '도른',
    '돌앗구만',
    '돌앗나',
    '돌앗네',
    '돌았구만',
    '돌았나',
    '돌았네',
    '둄마',
    '뒈져',
    '뒤져라',
    '뒤져버',
    '뒤져야',
    '뒤져야지',
    '뒤져요',
    '뒤졌',
    '뒤지겠',
    '뒤지고싶',
    '뒤지길',
    '뒤진다',
    '뒤질',
    '듣보',
    '디져라',
    '디졌',
    '디지고',
    '디질',
    '딴년',
    '또라이',
    '또라인',
    '똘아이',
    '뚝배기',
    '뚫린 입',
    '뚫린입',
    '런년',
    '레1친',
    '레기같',
    '레기네',
    '레기다',
    '레친',
    '롬들',
    'ㅁㅊ',
    'ㅁ친',
    '망돌',
    '망해라',
    '머갈',
    '머리 텅',
    '머리텅',
    '먹.금',
    '먹.끔',
    '먹1금',
    '먹금',
    '먹끔',
    '명존',
    '믜칀',
    '믜친',
    '미: 놈',
    '미:놈',
    '미1친',
    '미놈',
    '미시친발',
    '미쳣네',
    '미쳤나',
    '미쳤니',
    '미췬',
    '미칀',
    '미친 새',
    '미친~',
    '미친개',
    '미친새',
    '미친색',
    '미친ㅋ',
    '미틴',
    '및힌',
    '줘패',
    '꼬추',
    '미치ㄴ',
    'ㅅ.ㄲ',
    '색퀴',
    'ㅅ끼',
    '흉자',
    '미친넘',
    '미핀놈',
    '샛기',
    'G랄',
    '세키',
    '미치누',
    'd져',
    'ㅂㄹ',
    'ㅂㅁㄱ',
    'ㅂㅊ',
    'ㅂ크',
    '발놈',
    '별창',
    '병1신',
    '병1크',
    '병맛',
    '병신',
    '병크',
    '봊',
    '보전깨',
    '싸개',
    '븅신',
    '빠큐',
    '빡새끼',
    '빻았',
    '빻은',
    '뻐규',
    '뻐큐',
    '뻑유',
    '뻑큐',
    '뻨큐',
    '뼈큐',
    '뽄새',
    '뽄세',
    '삐걱',
    '쉰내',
    'ㅄ',
    'ㅅ.ㅂ',
    'ㅅ1ㅂ',
    'ㅅ1발',
    'ㅅㄲ네',
    'ㅅㄲ들',
    '친ㅅㄲ',
    '친 ㅅㄲ',
    'ㅅ1ㄲ',
    'ㅅ루',
    'ㅅㅋ',
    'ㅅㅌㅊ',
    'ㅅㅡ루',
    '사새끼',
    '새.끼',
    '새1끼',
    '새1키',
    '새77ㅣ',
    '새끼라',
    '새끼야',
    '새퀴',
    '새킈',
    '새키',
    '색희',
    '색히',
    '샊기',
    '샊히',
    '샹년',
    '섀키',
    '성괴',
    '쉬발',
    '쉬버',
    '쉬이바',
    '쉬이이',
    '쉬이이이',
    '쉬펄',
    '슈1발',
    '슈레기',
    '슈발',
    '슈벌',
    '슈우벌',
    '슈ㅣ발',
    '스.루',
    '스ㄹㅜ',
    '스벌',
    '싑창',
    '시1발',
    '시미발친',
    '시미친발',
    '시바 ',
    '시바라지',
    '시바류',
    '시바시바',
    '시바알',
    '시바앙',
    '시발',
    '🖕',
    '시방새',
    '시벌탱',
    '시볼탱',
    '시부럴',
    '시부렬',
    '시부울',
    '시뷰럴',
    '시뷰렬',
    '시빨',
    '시새발끼',
    '시이발',
    '시친발미',
    '시팔',
    '시펄',
    '십창',
    '십팔',
    'ㅆ1ㄺ',
    'ㅆ1ㅂ',
    'ㅆㄹㄱ',
    'ㅆㄺ',
    'ㅆㅂ',
    '싸가지 없',
    '싸가지없',
    '싸물어',
    '쌍년',
    '쌍놈',
    '쌔끼',
    '썅',
    '썌끼',
    '쒸펄',
    '쓰1레기',
    '쓰래기같',
    '쓰레기 새',
    '쓰레기새',
    '쓰렉',
    '씝창',
    '씨1발',
    '씨바라',
    '씨바알',
    '씨발',
    '씨방새',
    '씨버럼',
    '씨벌',
    '씨벌탱',
    '씨볼탱',
    '씨부럴',
    '씨부렬',
    '씨뷰럴',
    '씨뷰렬',
    '씨빠빠',
    '씨빨',
    '씨뻘',
    '씨새발끼',
    '씨이발',
    '씨팔',
    '씹귀',
    '씹덕',
    '씹못',
    '씹뻐럴',
    '씹새끼',
    '씹쌔',
    '씹창',
    '씹치',
    '씹팔',
    '씹할',
    'ㅇㅍㅊㅌ',
    '아가리',
    '아닥',
    '아오 ㅅㅂ',
    '아오 시바',
    '아오ㅅㅂ',
    '아오시바',
    '애미',
    '앰',
    '앰창',
    '에라이 퉤',
    '에라이 퉷',
    '에라이퉤',
    '에라이퉷',
    '엠뷩신',
    '엠븽신',
    '엠빙신',
    '시녀',
    '엠생',
    '엠창',
    '엿같',
    '엿이나',
    '옘병',
    '오크',
    '와꾸',
    '외1퀴',
    '외퀴',
    '웅앵',
    '웅엥',
    '은년',
    '은새끼',
    '이 새끼',
    '이따위',
    '이새끼',
    '인간말종',
    '입 털',
    '입털',
    'ㅈ.ㄴ',
    'ㅈㄴ',
    'ㅈㄹ',
    '절라',
    '정병',
    '정신나갓',
    '정신나갔',
    '젖 같',
    '젗같',
    '젼나',
    '젼낰',
    '졀라',
    '졀리',
    '졌같은',
    '졏 같',
    '조낸',
    '조녜',
    '조온',
    '조온나',
    '족까',
    '존 나',
    '존 나',
    '존.나',
    '존1',
    '존1나',
    '🚬',
    '존귀',
    '존귘',
    '존ㄴ나',
    '존나',
    '존낙',
    '존내',
    '존똑',
    '존맛',
    '존멋',
    '존버',
    '존싫',
    '존웃',
    '존잘',
    '존잼',
    '존좋',
    '졸라',
    '졸맛',
    '졸멋',
    '졸싫',
    '졸예',
    '졸웃',
    '졸잼',
    '졸좋',
    '좁밥',
    '조센징',
    '짱깨',
    '짱개',
    '짱꼴라',
    '짱골라',
    '좃',
    '종나',
    '곱창났',
    '곱창나',
    '좆',
    '좆까',
    '좇같',
    '죠낸',
    '죠온나',
    '죤나',
    '죤내',
    '죵나',
    '죶',
    '죽어버려',
    '죽여 버리고',
    '죽여버리고',
    '죽여불고',
    '죽여뿌고',
    '줬같은',
    '쥐랄',
    '쥰나',
    '쥰내',
    '쥰니',
    '쥰트',
    '즤랄',
    '지 랄',
    '지1랄',
    '지1뢰',
    '지랄',
    '지롤',
    'ㅉ',
    'ㅉ질한',
    '짱깨',
    '짱께',
    '쪼녜',
    '쪼다',
    '착짱죽짱',
    '섬숭이',
    '쪽본',
    '쪽1바리',
    '쪽바리',
    '쪽발',
    '쫀 맛',
    '쫀1',
    '쫀귀',
    '쫀맛',
    '쫂',
    '쫓같',
    '쬰잘',
    '쬲',
    '쯰질',
    '찌1질',
    '찌질한',
    '찍찍이',
    '찎찎이',
    '찝째끼',
    '창년',
    '창녀',
    '창남',
    '창놈',
    '창넘',
    '처먹',
    '凸',
    '첫빠',
    '취좃',
    '친 년',
    '한 년',
    '친 놈',
    '친구년',
    '친년',
    '한년',
    '친노마',
    '친놈',
    '텐덕',
    '핑끄',
    '핑프',
    'ㅎㅃ',
    'ㅎㅌㅊ',
    '손놈',
    '남미새',
    '여미새',
    '호로새끼',
    '호로잡',
    '화낭년',
    '화냥년',
    '후.려',
    '후1려',
    '후1빨',
    '후려',
    '후빨',
    '미-친',
    '시-발',
    '지-랄',
    '개-새-끼',
    '또-라-이',
    '디-질',
    '걸-레',
    '닥-쳐',
    '등-신',
    '뇌-텅텅',
    '대-가-리',
    '병-신',
    '엠-창',
    '조-ㅈ',
    '염-병',
    '쌍-판',
    '쳐-',
    '씹-',
        'ancuk',
    'ancok',
    'ajig',
    'anjay',
    'anjing',
    'anying',
    'anjir',
    'asu',
    'asyu',
    'babangus',
    'babi',
    'bacol',
    'bacot',
    'bagong',
    'bajingan',
    'balegug',
    'banci',
    'bangke',
    'bangsat',
    'bedebah',
    'bedegong',
    'bego',
    'belegug',
    'beloon',
    'bencong',
    'bloon',
    'bloon',
    'bodoh',
    'boloho',
    'buduk',
    'budug',
    'celeng',
    'cibai',
    'cibay',
    'cocot',
    'cocote',
    'cok',
    'cokil',
    'colai',
    'colay',
    'coli',
    'colmek',
    'conge',
    'congean',
    'congek',
    'congor',
    'cuk',
    'cukima',
    'cukimai',
    'cukimay',
    'dancok',
    'entot',
    'entotan',
    'ewe',
    'ewean',
    'gelo',
    'genjik',
    'germo',
    'gigolo',
    'goblo',
    'goblog',
    'goblok',
    'hencet',
    'henceut',
    'heunceut',
    'homo',
    'idiot',
    'itil',
    'jancuk',
    'jancok',
    'jablay',
    'jalang',
    'jembut',
    'jiancok',
    'jilmek',
    'jurig',
    'kacung',
    'kampang',
    'kampret',
    'kampungan',
    'kehed',
    'kenthu',
    'kentot',
    'kentu',
    'keparat',
    'kimak',
    'kintil',
    'kirik',
    'kunyuk',
    'kurap',
    'konti',
    'kontol',
    'kopet',
    'koplok',
    'lacur',
    'lebok',
    'lonte',
    'maho',
    'meki',
    'memek',
    'monyet',
    'ndas',
    'ndasmu',
    'ngehe',
    'ngentot',
    'nggateli',
    'nyepong',
    'ngewe',
    'ngocok',
    'pante',
    'pantek', 
    'patek',
    'pathek',
    'peju',
    'pejuh',
    'pecun',
    'pecundang',
    'pelacur',
    'pelakor',
    'peler',
    'pepek',
    'puki',
    'pukima',
    'pukimae',
    'pukimak',
    'pukimay',
    'sampah',
    'sepong',
    'sial',
    'sialan',
    'silit',
    'sinting',
    'sontoloyo',
    'tai',
    'taik',
    'tempek',
    'tempik',
    'tete',
    'tetek',
    'tiembokne',
    'titit',
    'toket',
    'tolol',
    'ublag',
    'udik',
    'wingkeng',
    'سكس',
    'طيز',
    'شرج',
    'لعق',
    'لحس',
    'مص',
    'تمص',
    'بيضان',
    'ثدي',
    'بز',
    'بزاز',
    'حلمة',
    'مفلقسة',
    'بظر',
    'كس',
    'فرج',
    'شهوة',
    'شاذ',
    'مبادل',
    'عاهرة',
    'جماع',
    'قضيب',
    'زب',
    'لوطي',
    'لواط',
    'سحاق',
    'سحاقية',
    'اغتصاب',
    'خنثي',
    'احتلام',
    'نيك',
    'متناك',
    'متناكة',
    'شرموطة',
    'عرص',
    'خول',
    'قحبة',
    'لبوة',
    'bordel',
    'buzna',
    'čumět',
    'čurák',
    'debil',
    'do piče',
    'do prdele',
    'dršťka',
    'držka',
    'flundra',
    'hajzl',
    'hovno',
    'chcanky',
    'chuj',
    'jebat',
    'kokot',
    'kokotina',
    'koňomrd',
    'kunda',
    'kurva',
    'mamrd',
    'mrdat',
    'mrdka',
    'mrdník',
    'oslošoust',
    'piča',
    'píčus',
    'píchat',
    'pizda',
    'prcat',
    'prdel',
    'prdelka',
    'sračka',
    'srát',
    'šoustat',
    'šulin',
    'vypíčenec',
    'zkurvit',
    'zkurvysyn',
    'zmrd',
    'žrát',
    'anus',
    'bøsserøv',
    'cock',
    'fisse',
    'fissehår',
    'fuck',
    'hestepik',
    'kussekryller',
    'lort',
    'luder',
    'pik',
    'pikhår',
    'pikslugeri',
    'piksutteri',
    'pis',
    'røv',
    'røvhul',
    'røvskæg',
    'røvspræke',
    'shit',
    'analritter',
    'arsch',
    'arschficker',
    'arschlecker',
    'arschloch',
    'bimbo',
    'bratze',
    'bumsen',
    'bonze',
    'dödel',
    'fick',
    'ficken',
    'flittchen',
    'fotze',
    'fratze',
    'hackfresse',
    'hure',
    'hurensohn',
    'ische',
    'kackbratze',
    'kacke',
    'kacken',
    'kackwurst',
    'kampflesbe',
    'kanake',
    'kimme',
    'lümmel',
    'MILF',
    'möpse',
    'morgenlatte',
    'möse',
    'mufti',
    'muschi',
    'nackt',
    'neger',
    'nigger',
    'nippel',
    'nutte',
    'onanieren',
    'orgasmus',
    'penis',
    'pimmel',
    'pimpern',
    'pinkeln',
    'pissen',
    'pisser',
    'popel',
    'poppen',
    'porno',
    'reudig',
    'rosette',
    'schabracke',
    'schlampe',
    'scheiße',
    'scheisser',
    'schiesser',
    'schnackeln',
    'schwanzlutscher',
    'schwuchtel',
    'tittchen',
    'titten',
    'vögeln',
    'vollpfosten',
    'wichse',
    'wichsen',
    'wichser',
    'realz fuck',
    'peelz fuck',
    'damn',
    '👌👈',
    'fucked',
    'mf',
    'lankybitches',
    'drugz',
    'fruck',
    'poopnose',
    'shitting penises',
    'fu<king',
    'pen1s',
    'milker',
    'h○e',
    'ørgasm',
    'b1t<h',
    'orgasm',
    'penises',
    'butch',
    'hole',
    '🍆',
    '🍑',
    'bitc',
    'sberm',
    'dilf',
    'drugs',
    'frick',
    'hell',
    'cvm',
    'penis',
    'balls',
    't!ties',
    'nazisnt',
    'sperm',
    'b1tch',
    'sh1t',
    'Mommy milkers',
    'nagga',
    'retard',
    'fuce',
    'botch',
    'wtf',
    '🖕',
    '2g1c',
    '2 girls 1 cup',
    'acrotomophilia',
    'alabama hot pocket',
    'alaskan pipeline',
    'anal',
    'anilingus',
    'anus',
    'apeshit',
    'arsehole',
    'ass',
    'asshole',
    'assmunch',
    'auto erotic',
    'autoerotic',
    'babeland',
    'baby batter',
    'baby juice',
    'ball gag',
    'ball gravy',
    'ball kicking',
    'ball licking',
    'ball sack',
    'ball sucking',
    'bangbros',
    'bangbus',
    'bareback',
    'barely legal',
    'barenaked',
    'bastard',
    'bastardo',
    'bastinado',
    'bbw',
    'bdsm',
    'beaner',
    'beaners',
    'beaver cleaver',
    'beaver lips',
    'beastiality',
    'bestiality',
    'big black',
    'big breasts',
    'big knockers',
    'big tits',
    'bimbos',
    'birdlock',
    'bitch',
    'bitches',
    'black cock',
    'blonde action',
    'blonde on blonde action',
    'blowjob',
    'blow job',
    'blow your load',
    'blue waffle',
    'blumpkin',
    'bollocks',
    'bondage',
    'boner',
    'boob',
    'boobs',
    'booty call',
    'brown showers',
    'brunette action',
    'bukkake',
    'bulldyke',
    'bullet vibe',
    'bullshit',
    'bung hole',
    'bunghole',
    'busty',
    'butt',
    'buttcheeks',
    'butthole',
    'camel toe',
    'camgirl',
    'camslut',
    'camwhore',
    'carpet muncher',
    'carpetmuncher',
    'chocolate rosebuds',
    'cialis',
    'circlejerk',
    'cleveland steamer',
    'clit',
    'clitoris',
    'clover clamps',
    'clusterfuck',
    'cock',
    'cocks',
    'coprolagnia',
    'coprophilia',
    'cornhole',
    'coon',
    'coons',
    'creampie',
    'cum',
    'cumming',
    'cumshot',
    'cumshots',
    'cunnilingus',
    'cunt',
    'darkie',
    'date rape',
    'daterape',
    'deep throat',
    'deepthroat',
    'dendrophilia',
    'dick',
    'dildo',
    'dingleberry',
    'dingleberries',
    'dirty pillows',
    'dirty sanchez',
    'doggie style',
    'doggiestyle',
    'doggy style',
    'doggystyle',
    'dog style',
    'dolcett',
    'domination',
    'dominatrix',
    'dommes',
    'donkey punch',
    'double dong',
    'double penetration',
    'dp action',
    'dry hump',
    'dvda',
    'eat my ass',
    'ecchi',
    'ejaculation',
    'erotic',
    'erotism',
    'escort',
    'eunuch',
    'fag',
    'faggot',
    'fecal',
    'felch',
    'fellatio',
    'feltch',
    'female squirting',
    'femdom',
    'figging',
    'fingerbang',
    'fingering',
    'fisting',
    'foot fetish',
    'footjob',
    'frotting',
    'fuck',
    'f1ck',
    'fucker',
    'fuck buttons',
    'fuckin',
    'fucking',
    'fucktards',
    'fudge packer',
    'fudgepacker',
    'futanari',
    'gangbang',
    'gang bang',
    'gay sex',
    'genitals',
    'giant cock',
    'girl on',
    'girl on top',
    'girls gone wild',
    'goatcx',
    'goatse',
    'god damn',
    'gokkun',
    'golden shower',
    'goodpoop',
    'goo girl',
    'goregasm',
    'grope',
    'group sex',
    'g-spot',
    'guro',
    'hand job',
    'handjob',
    'hard core',
    'hardcore',
    'hentai',
    'homoerotic',
    'honkey',
    'hooker',
    'horny',
    'hot carl',
    'hot chick',
    'how to kill',
    'how to murder',
    'huge fat',
    'humping',
    'incest',
    'intercourse',
    'jack off',
    'jail bait',
    'jailbait',
    'jelly donut',
    'jerk off',
    'jigaboo',
    'jiggaboo',
    'jiggerboo',
    'jizz',
    'juggs',
    'kike',
    'kinbaku',
    'kinkster',
    'kinky',
    'knobbing',
    'leather restraint',
    'leather straight jacket',
    'lemon party',
    'livesex',
    'lolita',
    'lovemaking',
    'make me come',
    'male squirting',
    'masturbate',
    'masturbating',
    'masturbation',
    'menage a trois',
    'milf',
    'missionary position',
    'mong',
    'motherfucker',
    'mound of venus',
    'mr hands',
    'muff diver',
    'muffdiving',
    'nambla',
    'nawashi',
    'negro',
    'neonazi',
    'nigga',
    'nigger',
    'nig nog',
    'nimphomania',
    'nipple',
    'nipples',
    'nsfw',
    'nsfw images',
    'nude',
    'nudity',
    'nutten',
    'nympho',
    'nymphomania',
    'octopussy',
    'omorashi',
    'one cup two girls',
    'one guy one jar',
    'orgy',
    'paedophile',
    'paki',
    'panties',
    'panty',
    'pedobear',
    'pedophile',
    'pegging',
    'phone sex',
    'piece of shit',
    'pikey',
    'pissing',
    'piss pig',
    'pisspig',
    'playboy',
    'pleasure chest',
    'pole smoker',
    'ponyplay',
    'poof',
    'poon',
    'poontang',
    'punany',
    'poop chute',
    'poopchute',
    'porn',
    'porno',
    'pornography',
    'prince albert piercing',
    'pthc',
    'pubes',
    'pussy',
    'queaf',
    'queef',
    'quim',
    'raghead',
    'raging boner',
    'rape',
    'raping',
    'rapist',
    'rectum',
    'reverse cowgirl',
    'rimjob',
    'rimming',
    'rosy palm',
    'rosy palm and her 5 sisters',
    'rusty trombone',
    'sadism',
    'santorum',
    'scat',
    'schlong',
    'scissoring',
    'semen',
    'sex',
    'sexcam',
    'sexo',
    'sexy',
    'sexual',
    'sexually',
    'sexuality',
    'shaved beaver',
    'shaved pussy',
    'shemale',
    'shibari',
    'shit',
    'shitblimp',
    'shitty',
    'shota',
    'shrimping',
    'skeet',
    'slanteye',
    'slut',
    's&m',
    'smut',
    'snatch',
    'snowballing',
    'sodomize',
    'sodomy',
    'spastic',
    'spic',
    'splooge',
    'splooge moose',
    'spooge',
    'spread legs',
    'spunk',
    'strap on',
    'strapon',
    'strappado',
    'strip club',
    'style doggy',
    'suck',
    'sucks',
    'suicide girls',
    'sultry women',
    'swastika',
    'swinger',
    'tainted love',
    'taste my',
    'tea bagging',
    'threesome',
    'throating',
    'thumbzilla',
    'tied up',
    'tight white',
    'tit',
    'tits',
    'titties',
    'titty',
    'tongue in a',
    'topless',
    'tosser',
    'towelhead',
    'tranny',
    'tribadism',
    'tub girl',
    'tubgirl',
    'tushy',
    'twat',
    'twink',
    'twinkie',
    'two girls one cup',
    'undressing',
    'upskirt',
    'urethra play',
    'urophilia',
    'vagina',
    'venus mound',
    'viagra',
    'vibrator',
    'violet wand',
    'vorarephilia',
    'voyeur',
    'voyeurweb',
    'voyuer',
    'vulva',
    'wank',
    'wetback',
    'wet dream',
    'white power',
    'whore',
    'worldsex',
    'wrapping men',
    'wrinkled starfish',
    'xx',
    'xxx',
    'yaoi',
    'yellow showers',
    'yiffy',
    'zoophilia',
    'bugren',
    'bugri',
    'bugru',
    'ĉiesulino',
    'ĉiesulo',
    'diofek',
    'diofeka',
    'fek',
    'feken',
    'fekfikanto',
    'feklekulo',
    'fekulo',
    'fik',
    'fikado',
    'fikema',
    'fikfek',
    'fiki',
    'fikiĝi',
    'fikiĝu',
    'fikilo',
    'fikklaŭno',
    'fikota',
    'fiku',
    'forfiki',
    'forfikiĝu',
    'forfiku',
    'forfurzu',
    'forpisi',
    'forpisu',
    'furzulo',
    'kacen',
    'kaco',
    'kacsuĉulo',
    'kojono',
    'piĉen',
    'piĉo',
    'zamenfek',
    'Asesinato',
    'asno',
    'bastardo',
    'Bollera',
    'Cabrón',
    'Caca',
    'Chupada',
    'Chupapollas',
    'Chupetón',
    'concha',
    'Concha de tu madre',
    'Coño',
    'Coprofagía',
    'Culo',
    'Drogas',
    'Esperma',
    'Fiesta de salchichas',
    'Follador',
    'Follar',
    'Gilipichis',
    'Gilipollas',
    'Hacer una paja',
    'Haciendo el amor',
    'Heroína',
    'Hija de puta',
    'Hijaputa',
    'Hijo de puta',
    'Hijoputa',
    'Idiota',
    'Imbécil',
    'infierno',
    'Jilipollas',
    'Kapullo',
    'Lameculos',
    'Maciza',
    'Macizorra',
    'maldito',
    'Mamada',
    'Marica',
    'Maricón',
    'Mariconazo',
    'martillo',
    'Mierda',
    'Nazi',
    'Orina',
    'Pedo',
    'Pendejo',
    'Pervertido',
    'Pezón',
    'Pinche',
    'Pis',
    'Prostituta',
    'Puta',
    'Racista',
    'Ramera',
    'Sádico',
    'Semen',
    'Sexo',
    'Sexo oral',
    'Soplagaitas',
    'Soplapollas',
    'Tetas grandes',
    'Tía buena',
    'Travesti',
    'Trio',
    'Verga',
    'vete a la mierda',
    'Vulva',
    'آب کیر',
    'ارگاسم',
    'برهنه',
    'پورن',
    'پورنو',
    'تجاوز',
    'تخمی',
    'جق',
    'جقی',
    'جلق',
    'جنده',
    'چوچول',
    'حشر',
    'حشری',
    'داف',
    'دودول',
    'ساک زدن',
    'سکس',
    'سکس کردن',
    'سکسی',
    'سوپر',
    'شق کردن',
    'شهوت',
    'شهوتی',
    'شونبول',
    'فیلم سوپر',
    'کس',
    'کس دادن',
    'کس کردن',
    'کسکش',
    'کوس',
    'کون',
    'کون دادن',
    'کون کردن',
    'کونکش',
    'کونی',
    'کیر',
    'کیری',
    'لاپا',
    'لاپایی',
    'لاشی',
    'لخت',
    'لش',
    'منی',
    'هرزه',
    'alfred nussi',
    'bylsiä',
    'haahka',
    'haista paska',
    'haista vittu',
    'hatullinen',
    'helvetisti',
    'hevonkuusi',
    'hevonpaska',
    'hevonperse',
    'hevonvittu',
    'hevonvitunperse',
    'hitosti',
    'hitto',
    'huorata',
    'hässiä',
    'juosten kustu',
    'jutku',
    'jutsku',
    'jätkä',
    'kananpaska',
    'koiranpaska',
    'kuin esterin perseestä',
    'kulli',
    'kullinluikaus',
    'kuppainen',
    'kusaista',
    'kuseksia',
    'kusettaa',
    'kusi',
    'kusipää',
    'kusta',
    'kyrpiintynyt',
    'kyrpiintyä',
    'kyrpiä',
    'kyrpä',
    'kyrpänaama',
    'kyrvitys',
    'lahtari',
    'lutka',
    'molo',
    'molopää',
    'mulkero',
    'mulkku',
    'mulkvisti',
    'muna',
    'munapää',
    'munaton',
    'mutakuono',
    'mutiainen',
    'naida',
    'nainti',
    'narttu',
    'neekeri',
    'nekru',
    'nuolla persettä',
    'nussia',
    'nussija',
    'nussinta',
    'paljaalla',
    'palli',
    'pallit',
    'paneskella',
    'panettaa',
    'panna',
    'pano',
    'pantava',
    'paska',
    'paskainen',
    'paskamainen',
    'paskanmarjat',
    'paskantaa',
    'paskapuhe',
    'paskapää',
    'paskattaa',
    'paskiainen',
    'paskoa',
    'pehko',
    'pentele',
    'perkele',
    'perkeleesti',
    'persaukinen',
    'perse',
    'perseennuolija',
    'perseet olalla',
    'persereikä',
    'perseääliö',
    'persläpi',
    'perspano',
    'persvako',
    'pilkunnussija',
    'pillu',
    'pillut',
    'pipari',
    'piru',
    'pistää',
    'pyllyvako',
    'reikä',
    'reva',
    'ripsipiirakka',
    'runkata',
    'runkkari',
    'runkkaus',
    'runkku',
    'ryssä',
    'rättipää',
    'saatanasti',
    'suklaaosasto',
    'tavara',
    'toosa',
    'tuhkaluukku',
    'tumputtaa',
    'turpasauna',
    'tussu',
    'tussukka',
    'tussut',
    'vakipano',
    'vetää käteen',
    'viiksi',
    'vittu',
    'vittuilla',
    'vittuilu',
    'vittumainen',
    'vittuuntua',
    'vittuuntunut',
    'vitun',
    'vitusti',
    'vituttaa',
    'vitutus',
    'äpärä',
    'puta ka',
    'putang ina',
    'tang ina',
    'tangina',
    'burat',
    'bayag',
    'bobo',
    'nognog',
    'tanga',
    'ulol',
    'kantot',
    'anak ka ng puta',
    'jakol',
    'baiser',
    'bander',
    'bigornette',
    'bite',
    'bitte',
    'bloblos',
    'bordel',
    'bourré',
    'bourrée',
    'brackmard',
    'branlage',
    'branler',
    'branlette',
    'branleur',
    'branleuse',
    'brouter le cresson',
    'caca',
    'chatte',
    'chiasse',
    'chier',
    'chiottes',
    'clito',
    'clitoris',
    'con',
    'connard',
    'connasse',
    'conne',
    'couilles',
    'cramouille',
    'cul',
    'déconne',
    'déconner',
    'emmerdant',
    'emmerder',
    'emmerdeur',
    'emmerdeuse',
    'enculé',
    'enculée',
    'enculeur',
    'enculeurs',
    'enfoiré',
    'enfoirée',
    'étron',
    'fille de pute',
    'fils de pute',
    'folle',
    'foutre',
    'gerbe',
    'gerber',
    'gouine',
    'grande folle',
    'grogniasse',
    'gueule',
    'jouir',
    'la putain de ta mère',
    'MALPT',
    'ménage à trois',
    'merde',
    'merdeuse',
    'merdeux',
    'meuf',
    'nègre',
    'negro',
    'nique ta mère',
    'nique ta race',
    'palucher',
    'pédale',
    'pédé',
    'péter',
    'pipi',
    'pisser',
    'pouffiasse',
    'pousse-crotte',
    'putain',
    'pute',
    'ramoner',
    'sac à foutre',
    'sac à merde',
    'salaud',
    'salope',
    'suce',
    'tapette',
    'tanche',
    'teuch',
    'tringler',
    'trique',
    'troncher',
    'trou du cul',
    'turlute',
    'zigounette',
    'zizi',
    'aand',
    'aandu',
    'balatkar',
    'balatkari',
    'behen chod',
    'beti chod',
    'bhadva',
    'bhadve',
    'bhandve',
    'bhangi',
    'bhootni ke',
    'bhosad',
    'bhosadi ke',
    'boobe',
    'chakke',
    'chinaal',
    'chinki',
    'chod',
    'chodu',
    'chodu bhagat',
    'chooche',
    'choochi',
    'choope',
    'choot',
    'choot ke baal',
    'chootia',
    'chootiya',
    'chuche',
    'chuchi',
    'chudaap',
    'chudai khanaa',
    'chudam chudai',
    'chude',
    'chut',
    'chut ka chuha',
    'chut ka churan',
    'chut ka mail',
    'chut ke baal',
    'chut ke dhakkan',
    'chut maarli',
    'chutad',
    'chutadd',
    'chutan',
    'chutia',
    'chutiya',
    'gaand',
    'gaandfat',
    'gaandmasti',
    'gaandufad',
    'gandfattu',
    'gandu',
    'gashti',
    'gasti',
    'ghassa',
    'ghasti',
    'gucchi',
    'gucchu',
    'harami',
    'haramzade',
    'hawas',
    'hawas ke pujari',
    'hijda',
    'hijra',
    'jhant',
    'jhant chaatu',
    'jhant ka keeda',
    'jhant ke baal',
    'jhant ke pissu',
    'jhantu',
    'kamine',
    'kaminey',
    'kanjar',
    'kutta',
    'kutta kamina',
    'kutte ki aulad',
    'kutte ki jat',
    'kuttiya',
    'loda',
    'lodu',
    'lund',
    'lund choos',
    'lund ka bakkal',
    'lund khajoor',
    'lundtopi',
    'lundure',
    'maa ki chut',
    'maal',
    'madar chod',
    'madarchod',
    'madhavchod',
    'mooh mein le',
    'mutth',
    'mutthal',
    'najayaz',
    'najayaz aulaad',
    'najayaz paidaish',
    'paki',
    'pataka',
    'patakha',
    'raand',
    'randaap',
    'randi',
    'randi rona',
    'saala',
    'saala kutta',
    'saali kutti',
    'saali randi',
    'suar',
    'suar ke lund',
    'suar ki aulad',
    'tatte',
    'tatti',
    'teri maa ka bhosada',
    'teri maa ka boba chusu',
    'teri maa ki behenchod ',
    'teri maa ki chut',
    'tharak',
    'tharki',
    'tu chuda',
    'balfasz',
    'balfaszok',
    'balfaszokat',
    'balfaszt',
    'barmok',
    'barmokat',
    'barmot',
    'barom',
    'baszik',
    'bazmeg',
    'buksza',
    'bukszák',
    'bukszákat',
    'bukszát',
    'búr',
    'búrok',
    'csöcs',
    'csöcsök',
    'csöcsöket',
    'csöcsöt',
    'fasz',
    'faszfej',
    'faszfejek',
    'faszfejeket',
    'faszfejet',
    'faszok',
    'faszokat',
    'faszt',
    'fing',
    'fingok',
    'fingokat',
    'fingot',
    'franc',
    'francok',
    'francokat',
    'francot',
    'geci',
    'gecibb',
    'gecik',
    'geciket',
    'gecit',
    'kibaszott',
    'kibaszottabb',
    'kúr',
    'kurafi',
    'kurafik',
    'kurafikat',
    'kurafit',
    'kurva',
    'kurvák',
    'kurvákat',
    'kurvát',
    'leggecibb',
    'legkibaszottabb',
    'legszarabb',
    'marha',
    'marhák',
    'marhákat',
    'marhát',
    'megdöglik',
    'pele',
    'pelék',
    'picsa',
    'picsákat',
    'picsát',
    'pina',
    'pinák',
    'pinákat',
    'pinát',
    'pofa',
    'pofákat',
    'pofát',
    'pöcs',
    'pöcsök',
    'pöcsöket',
    'pöcsöt',
    'punci',
    'puncik',
    'segg',
    'seggek',
    'seggeket',
    'segget',
    'seggfej',
    'seggfejek',
    'seggfejeket',
    'seggfejet',
    'szajha',
    'szajhák',
    'szajhákat',
    'szajhát',
    'szar',
    'szarabb',
    'szarik',
    'szarok',
    'szarokat',
    'szart',
    'allupato',
    'ammucchiata',
    'anale',
    'arrapato',
    'arrusa',
    'arruso',
    'assatanato',
    'bagascia',
    'bagassa',
    'bagnarsi',
    'baldracca',
    'balle',
    'battere',
    'battona',
    'belino',
    'biga',
    'bocchinara',
    'bocchino',
    'bofilo',
    'boiata',
    'bordello',
    'brinca',
    'bucaiolo',
    'budiùlo',
    'busone',
    'cacca',
    'caciocappella',
    'cadavere',
    'cagare',
    'cagata',
    'cagna',
    'casci',
    'cazzata',
    'cazzimma',
    'cazzo',
    'cesso',
    'cazzone',
    'checca',
    'chiappa',
    'chiavare',
    'chiavata',
    'ciospo',
    'ciucciami il cazzo',
    'coglione',
    'coglioni',
    'cornuto',
    'cozza',
    'culattina',
    'culattone',
    'culo',
    'ditalino',
    'fava',
    'femminuccia',
    'fica',
    'figa',
    'figlio di buona donna',
    'figlio di puttana',
    'figone',
    'finocchio',
    'fottere',
    'fottersi',
    'fracicone',
    'fregna',
    'frocio',
    'froscio',
    'goldone',
    'guardone',
    'imbecille',
    'incazzarsi',
    'incoglionirsi',
    'ingoio',
    'leccaculo',
    'lecchino',
    'lofare',
    'loffa',
    'loffare',
    'mannaggia',
    'merda',
    'merdata',
    'merdoso',
    'mignotta',
    'minchia',
    'minchione',
    'mona',
    'monta',
    'montare',
    'mussa',
    'nave scuola',
    'nerchia',
    'padulo',
    'palle',
    'palloso',
    'patacca',
    'patonza',
    'pecorina',
    'pesce',
    'picio',
    'pincare',
    'pippa',
    'pinnolone',
    'pipì',
    'pippone',
    'pirla',
    'pisciare',
    'piscio',
    'pisello',
    'pistolotto',
    'pomiciare',
    'pompa',
    'pompino',
    'porca',
    'porca madonna',
    'porca miseria',
    'porca puttana',
    'porco',
    'porco due',
    'porco zio',
    'potta',
    'puppami',
    'puttana',
    'quaglia',
    'recchione',
    'regina',
    'rincoglionire',
    'rizzarsi',
    'rompiballe',
    'rompipalle',
    'ruffiano',
    'sbattere',
    'sbattersi',
    'sborra',
    'sborrata',
    'sborrone',
    'sbrodolata',
    'scopare',
    'scopata',
    'scorreggiare',
    'slinguare',
    'slinguata',
    'smandrappata',
    'soccia',
    'socmel',
    'sorca',
    'spagnola',
    'spompinare',
    'sticchio',
    'stronza',
    'stronzata',
    'stronzo',
    'succhiami',
    'succhione',
    'sveltina',
    'sverginare',
    'tarzanello',
    'terrone',
    'testa di cazzo',
    'tette',
    'tirare',
    'topa',
    'troia',
    'trombare',
    'vacca',
    'vaffanculo',
    'vangare',
    'zinne',
    'zio cantante',
    'zoccola',
    '3p',
    'g スポット',
    's ＆ m',
    'sm',
    'sm女王',
    'xx',
    'アジアのかわいい女の子',
    'アスホール',
    'アナリングス',
    'アナル',
    'いたずら',
    'イラマチオ',
    'エクスタシー',
    'エスコート',
    'エッチ',
    'エロティズム',
    'エロティック',
    'オーガズム',
    'オカマ',
    'おしっこ',
    'おしり',
    'オシリ',
    'おしりのあな',
    'おっぱい',
    'オッパイ',
    'オナニー',
    'オマンコ',
    'おもらし',
    'お尻',
    'カーマスートラ',
    'カント',
    'クリトリス',
    'グループ・セックス',
    'グロ',
    'クンニリングス',
    'ゲイ・セックス',
    'ゲイボーイ',
    'ゴールデンシャワー',
    'コカイン',
    'ゴックン',
    'サディズム',
    'しばり',
    'スウィンガー',
    'スカートの中',
    'スカトロ',
    'ストラップオン',
    'ストリップ劇場',
    'スラット',
    'スリット',
    'セクシーな',
    'セクシーな 10 代',
    'セックス',
    'ソドミー',
    'ちんこ',
    'ディープ・スロート',
    'ディック',
    'ディルド',
    'デートレイプ',
    'デブ',
    'テレフォンセックス',
    'ドッグスタイル',
    'トップレス',
    'なめ',
    'ニガー',
    'ヌード',
    'ネオ・ナチ',
    'ハードコア',
    'パイパン',
    'バイブレーター',
    'バック・スタイル',
    'パンティー',
    'ビッチ',
    'ファック',
    'ファンタジー',
    'フィスト',
    'フェティッシュ',
    'フェラチオ',
    'ふたなり',
    'ぶっかけ',
    'フック',
    'プリンス アルバート ピアス',
    'プレイボーイ',
    'ベアバック',
    'ペニス',
    'ペニスバンド',
    'ボーイズラブ',
    'ボールギャグ',
    'ぽっちゃり',
    'ホモ',
    'ポルノ',
    'ポルノグラフィー',
    'ボンテージ',
    'マザー・ファッカー',
    'マスターベーション',
    'まんこ',
    'やおい',
    'やりまん',
    'ラティーナ',
    'ラバー',
    'ランジェリー',
    'レイプ',
    'レズビアン',
    'ローター',
    'ロリータ',
    '淫乱',
    '陰毛',
    '革抑制',
    '騎上位',
    '巨根',
    '巨乳',
    '強姦犯',
    '玉なめ',
    '玉舐め',
    '緊縛',
    '近親相姦',
    '嫌い',
    '後背位',
    '合意の性交',
    '拷問',
    '殺し方',
    '殺人事件',
    '殺人方法',
    '支配',
    '児童性虐待',
    '自己愛性',
    '射精',
    '手コキ',
    '獣姦',
    '女の子',
    '女王様',
    '女子高生',
    '女装',
    '新しいポルノ',
    '人妻',
    '人種',
    '性交',
    '正常位',
    '生殖器',
    '精液',
    '挿入',
    '足フェチ',
    '足を広げる',
    '大陰唇',
    '脱衣',
    '茶色のシャワー',
    '中出し',
    '潮吹き女',
    '潮吹き男性',
    '直腸',
    '剃毛',
    '貞操帯',
    '奴隷',
    '二穴',
    '乳首',
    '尿道プレイ',
    '覗き',
    '売春婦',
    '縛り',
    '噴出',
    '糞',
    '糞尿愛好症',
    '糞便',
    '平手打ち',
    '変態',
    '勃起する',
    '夢精',
    '毛深い',
    '誘惑',
    '幼児性愛者',
    '裸',
    '裸の女性',
    '乱交',
    '両性',
    '両性具有',
    '両刀',
    '輪姦',
    '卍',
    '宦官',
    '肛門',
    '膣',
    'abbuc',
    'aεeṭṭuḍ',
    'aḥeččun',
    'taḥeččunt',
    'axuzziḍ',
    'asxuẓeḍ',
    'qqu',
    'qquɣ',
    'qqiɣ',
    'qqan',
    'qqant',
    'tteqqun',
    'tteqqunt',
    'aqerqur',
    'ajeḥniḍ',
    'awellaq',
    'iwellaqen',
    'iḥeččan',
    'iḥeččunen',
    'uqan',
    'taxna',
    '강간',
    '개새끼',
    '개자식',
    '개좆',
    '개차반',
    '거유',
    '계집년',
    '고자',
    '근친',
    '노모',
    '니기미',
    '뒤질래',
    '딸딸이',
    '때씹',
    '또라이',
    '뙤놈',
    '로리타',
    '망가',
    '몰카',
    '미친',
    '미친새끼',
    '바바리맨',
    '변태',
    '병신',
    '보지',
    '불알',
    '빠구리',
    '사까시',
    '섹스',
    '스와핑',
    '쌍놈',
    '씨발',
    '씨발놈',
    '씨팔',
    '씹',
    '씹물',
    '씹빨',
    '씹새끼',
    '씹알',
    '씹창',
    '씹팔',
    '암캐',
    '애자',
    '야동',
    '야사',
    '야애니',
    '엄창',
    '에로',
    '염병',
    '옘병',
    '유모',
    '육갑',
    '은꼴',
    '자위',
    '자지',
    '잡년',
    '종간나',
    '좆',
    '좆만',
    '죽일년',
    '쥐좆',
    '직촬',
    '짱깨',
    '쪽바리',
    '창녀',
    '포르노',
    '하드코어',
    '호로',
    '화냥년',
    '후레아들',
    '후장',
    '희쭈그리',
    'aardappels afgieten',
    'achter het raam zitten',
    'afberen',
    'aflebberen',
    'afrossen',
    'afrukken',
    'aftrekken',
    'afwerkplaats',
    'afzeiken',
    'afzuigen',
    'een halve man en een paardekop',
    'anita',
    'asbak',
    'aso',
    'bagger schijten',
    'balen',
    'bedonderen',
    'befborstel',
    'beffen',
    'bekken',
    'belazeren',
    'besodemieterd zijn',
    'besodemieteren',
    'beurt',
    'boemelen',
    'boerelul',
    'boerenpummel',
    'bokkelul',
    'botergeil',
    'broekhoesten',
    'brugpieper',
    'buffelen',
    'buiten de pot piesen',
    'das kloten van de bok',
    'de ballen',
    'de hoer spelen',
    'de hond uitlaten',
    'de koffer induiken',
    'del',
    'de pijp uitgaan',
    'dombo',
    'draaikont',
    'driehoog achter wonen',
    'drol',
    'drooggeiler',
    'droogkloot',
    'een beurt geven',
    'een nummertje maken',
    'een wip maken',
    'eikel',
    'engerd',
    'flamoes',
    'flikken',
    'flikker',
    'gadverdamme',
    'galbak',
    'gat',
    'gedoogzone',
    'geilneef',
    'gesodemieter',
    'godverdomme',
    'graftak',
    'gras maaien',
    'gratenkut',
    'greppeldel',
    'griet',
    'hoempert',
    'hoer',
    'hoerenbuurt',
    'hoerenloper',
    'hoerig',
    'hol',
    'hufter',
    'huisdealer',
    'johny',
    'kanen',
    'kettingzeug',
    'klaarkomen',
    'klerebeer',
    'klojo',
    'klooien',
    'klootjesvolk',
    'klootoog',
    'klootzak',
    'kloten',
    'knor',
    'kont',
    'kontneuken',
    'krentekakker',
    'kut',
    'kuttelikkertje',
    'kwakkie',
    'liefdesgrot',
    'lul',
    'lul-de-behanger',
    'lulhannes',
    'lummel',
    'mafketel',
    'matennaaier',
    'matje',
    'mof',
    'muts',
    'naaien',
    'naakt',
    'neuken',
    'neukstier',
    'nicht',
    'oetlul',
    'opgeilen',
    'opkankeren',
    'oprotten',
    'opsodemieteren',
    'op zn hondjes',
    'op zn sodemieter geven',
    'opzouten',
    'ouwehoer',
    'ouwehoeren',
    'ouwe rukker',
    'paal',
    'paardelul',
    'palen',
    'penoze',
    'piesen',
    'pijpbekkieg',
    'pijpen',
    'pik',
    'pleurislaaier',
    'poep',
    'poepen',
    'poot',
    'portiekslet',
    'pot',
    'potverdorie',
    'publiciteitsgeil',
    'raaskallen',
    'reet',
    'reetridder',
    'reet trappen, voor zijn',
    'remsporen',
    'reutelen',
    'rothoer',
    'rotzak',
    'rukhond',
    'rukken',
    'schatje',
    'schijt',
    'schijten',
    'schoft',
    'schuinsmarcheerder',
    'shit',
    'slempen',
    'slet',
    'sletterig',
    'slik mijn zaad',
    'snol',
    'spuiten',
    'standje',
    'standje-69',
    'stoephoer',
    'stootje',
    'stront',
    'sufferd',
    'tapijtnek',
    'teef',
    'temeier',
    'teringlijer',
    'toeter',
    'tongzoeng',
    'triootjeg',
    'trottoir prostituée',
    'trottoirteef',
    'vergallen',
    'verkloten',
    'verneuken',
    'viespeuk',
    'vingeren',
    'vleesroos',
    'voor jan lul',
    'voor jan-met-de-korte-achternaam',
    'watje',
    'welzijnsmafia',
    'wijf',
    'wippen',
    'wuftje',
    'zaadje',
    'zakkenwasser',
    'zeiken',
    'zeiker',
    'zuigen',
    'zuiplap',
    'asshole',
    'dritt',
    'drittsekk',
    'faen',
    'faen i helvete',
    'fan',
    'fanken',
    'fitte',
    'forbanna',
    'forbannet',
    'forjævlig',
    'fuck',
    'fy faen',
    'føkk',
    'føkka',
    'føkkings',
    'jævla',
    'jævlig',
    'helvete',
    'helvetet',
    'kuk',
    'kukene',
    'kuker',
    'morraknuller',
    'morrapuler',
    'nigger',
    'pakkis',
    'pikk',
    'pokker',
    'ræva',
    'ræven',
    'satan',
    'shit',
    'sinnsykt',
    'skitt',
    'sotrør',
    'ståpikk',
    'ståpikkene',
    'ståpikker',
    'svartheiteste',
    'burdel',
    'burdelmama',
    'chuj',
    'chujnia',
    'ciota',
    'cipa',
    'cyc',
    'debil',
    'dmuchać',
    'do kurwy nędzy',
    'dupa',
    'dupek',
    'duperele',
    'dziwka',
    'fiut',
    'gówno',
    'gówno prawda',
    'huj',
    'huj ci w dupę',
    'jajco',
    'jajko',
    'ja pierdolę',
    'jebać',
    'jebany',
    'kurwa',
    'kurwy',
    'kutafon',
    'kutas',
    'lizać pałę',
    'obciągać chuja',
    'obciągać fiuta',
    'obciągać loda',
    'pieprzyć',
    'pierdolec',
    'pierdolić',
    'pierdolnąć',
    'pierdolnięty',
    'pierdoła',
    'pierdzieć',
    'pizda',
    'pojeb',
    'pojebany',
    'popierdolony',
    'robic loda',
    'robić loda',
    'ruchać',
    'rzygać',
    'skurwysyn',
    'sraczka',
    'srać',
    'suka',
    'syf',
    'wkurwiać',
    'zajebisty',
    'aborto',
    'arrombado',
    'ânus',
    'aranha',
    'ariano',
    'balalao',
    'bastardo',
    'bicha',
    'biscate',
    'bissexual',
    'boceta',
    'boob',
    'bosta',
    'braulio de borracha',
    'bumbum',
    'burro',
    'cabrao',
    'cacete',
    'caralho',
    'cagar',
    'camisinha',
    'cerveja',
    'chochota',
    'chupar',
    'clitoris',
    'cocaína',
    'coito',
    'colhoes',
    'comer',
    'cona',
    'consolo',
    'corno',
    'cu',
    'dar o rabo',
    'dum raio',
    'esporra',
    'fecal',
    'filho da puta',
    'foda',
    'foda-se',
    'foder',
    'fuder',
    'frango assado',
    'gozar',
    'grelho',
    'heroína',
    'heterosexual',
    'homem gay',
    'homoerótico',
    'homosexual',
    'inferno',
    'lésbica',
    'lolita',
    'mama',
    'merda',
    'nudes',
    'paneleiro',
    'passar um cheque',
    'pau',
    'peidar',
    'pênis',
    'pinto',
    'porra',
    'puta',
    'puta que pariu',
    'puta que te pariu',
    'queca',
    'sacanagem',
    'saco',
    'torneira',
    'transar',
    'vadia',
    'vai-te foder',
    'vai tomar no cu',
    'viado',
    'vibrador',
    'xana',
    'xochota',
    'bychara',
    'byk',
    'chernozhopyi',
    'dolboyeb',
    'ebalnik',
    'ebalo',
    'ebalom schelkat',
    'gol',
    'mudack',
    'opizdenet',
    'ostoeblo',
    'ostokhuitelno',
    'otebis',
    'otmudohat',
    'otpizdit',
    'otsosi',
    'padlo',
    'pedik',
    'perdet',
    'petuh',
    'pidar gnoinyj',
    'pizda',
    'pizdato',
    'pizdatyi',
    'pizdet',
    'pizdetc',
    'pizdoi nakrytsja',
    'pizduk',
    'piz`dyulina',
    'podi kuevo',
    'poeben',
    'poimat na konchik',
    'poiti posrat',
    'po khuy',
    'poluchit pizdy',
    'pososi moyu konfetku',
    'prissat',
    'proebat',
    'promudobladsksya pizdoproebina',
    'propezdoloch',
    'prosrat',
    'raspeezdeyi',
    'raspizdatyi',
    'razyebuy',
    'razyoba',
    'sebatsya',
    'shalava',
    'styervo',
    'sukin syn',
    'svodit posrat',
    'svoloch',
    'trakhatsya',
    'trimandoblydskiy pizdoproyob',
    'ublyudok',
    'uboy',
    'uebitsche',
    'vafla',
    'vafli lovit',
    'v pizdu',
    'vyperdysh',
    'vzdrochennyi',
    'yeb vas',
    'zaebat',
    'zaebis',
    'zalupa',
    'zalupat',
    'zasranetc',
    'zassat',
    'zloebuchy',
    'бздёнок',
    'блядки',
    'блядовать',
    'блядство',
    'блядь',
    'бугор',
    'во пизду',
    'встать раком',
    'выёбываться',
    'гандон',
    'говно',
    'говнюк',
    'голый',
    'дать пизды',
    'дерьмо',
    'дрочить',
    'другой дразнится',
    'ёбарь',
    'ебать',
    'ебать-копать',
    'ебло',
    'ебнуть',
    'ёб твою мать',
    'жопа',
    'жополиз',
    'играть на кожаной флейте',
    'измудохать',
    'каждый дрочит как он хочет',
    'какая разница',
    'как два пальца обоссать',
    'курите мою трубку',
    'лысого в кулаке гонять',
    'малофья',
    'манда',
    'мандавошка',
    'мент',
    'муда',
    'мудило',
    'мудозвон',
    'наебать',
    'наебениться',
    'наебнуться',
    'на фиг',
    'на хуй',
    'на хую вертеть',
    'на хуя',
    'нахуячиться',
    'невебенный',
    'не ебет',
    'ни за хуй собачу',
    'ни хуя',
    'обнаженный',
    'обоссаться можно',
    'один ебётся',
    'опесдол',
    'офигеть',
    'охуеть',
    'охуительно',
    'половое сношение',
    'секс',
    'сиськи',
    'спиздить',
    'срать',
    'ссать',
    'траxать',
    'ты мне ваньку не валяй',
    'фига',
    'хапать',
    'хер с ней',
    'хер с ним',
    'хохол',
    'хрен',
    'хуёво',
    'хуёвый',
    'хуем груши околачивать',
    'хуеплет',
    'хуило',
    'хуиней страдать',
    'хуиня',
    'хуй',
    'хуйнуть',
    'хуй пинать',
    'arsle',
    'brutta',
    'discofitta',
    'dra åt helvete',
    'fan',
    'fitta',
    'fittig',
    'för helvete',
    'helvete',
    'hård',
    'jävlar',
    'knulla',
    'kuk',
    'kuksås',
    'kötthuvud',
    'köttnacke',
    'moona',
    'moonade',
    'moonar',
    'moonat',
    'mutta',
    'nigger',
    'neger',
    'olla',
    'pippa',
    'pitt',
    'prutt',
    'pök',
    'runka',
    'röv',
    'rövhål',
    'rövknulla',
    'satan',
    'skita',
    'skit ner dig',
    'skäggbiff',
    'snedfitta',
    'snefitta',
    'stake',
    'subba',
    'sås',
    'sätta på',
    'tusan',
    'กระดอ',
    'กระเด้า',
    'กระหรี่',
    'กะปิ',
    'กู',
    'ขี้',
    'ควย',
    'จิ๋ม',
    'จู๋',
    'เจ๊ก',
    'เจี๊ยว',
    'ดอกทอง',
    'ตอแหล',
    'ตูด',
    'น้ําแตก',
    'มึง',
    'แม่ง',
    'เย็ด',
    'รูตูด',
    'ล้างตู้เย็น',
    'ส้นตีน',
    'สัด',
    'เสือก',
    'หญิงชาติชั่ว',
    'หลั่ง',
    'ห่า',
    'หํา',
    'หี',
    'เหี้ย',
    'อมนกเขา',
    'ไอ้ควาย',
    'ghuycha',
    'QIyaH',
    'Quvatlh',
    'amcığa',
    'amcığı',
    'amcığın',
    'amcık',
    'amcıklar',
    'amcıklara',
    'amcıklarda',
    'amcıklardan',
    'amcıkları',
    'amcıkların',
    'amcıkta',
    'amcıktan',
    'amı',
    'amlar',
    'çingene',
    'Çingenede',
    'Çingeneden',
    'Çingeneler',
    'Çingenelerde',
    'Çingenelerden',
    'Çingenelere',
    'Çingeneleri',
    'Çingenelerin',
    'Çingenenin',
    'Çingeneye',
    'Çingeneyi',
    'göt',
    'göte',
    'götler',
    'götlerde',
    'götlerden',
    'götlere',
    'götleri',
    'götlerin',
    'götte',
    'götten',
    'götü',
    'götün',
    'götveren',
    'götverende',
    'götverenden',
    'götverene',
    'götvereni',
    'götverenin',
    'götverenler',
    'götverenlerde',
    'götverenlerden',
    'götverenlere',
    'götverenleri',
    'götverenlerin',
    'kaltağa',
    'kaltağı',
    'kaltağın',
    'kaltak',
    'kaltaklar',
    'kaltaklara',
    'kaltaklarda',
    'kaltaklardan',
    'kaltakları',
    'kaltakların',
    'kaltakta',
    'kaltaktan',
    'orospu',
    'orospuda',
    'orospudan',
    'orospular',
    'orospulara',
    'orospularda',
    'orospulardan',
    'orospuları',
    'orospuların',
    'orospunun',
    'orospuya',
    'orospuyu',
    'otuz birci',
    'otuz bircide',
    'otuz birciden',
    'otuz birciler',
    'otuz bircilerde',
    'otuz bircilerden',
    'otuz bircilere',
    'otuz bircileri',
    'otuz bircilerin',
    'otuz bircinin',
    'otuz birciye',
    'otuz birciyi',
    'saksocu',
    'saksocuda',
    'saksocudan',
    'saksocular',
    'saksoculara',
    'saksocularda',
    'saksoculardan',
    'saksocuları',
    'saksocuların',
    'saksocunun',
    'saksocuya',
    'saksocuyu',
    'sıçmak',
    'sik',
    'sike',
    'siker sikmez',
    'siki',
    'sikilir sikilmez',
    'sikin',
    'sikler',
    'siklerde',
    'siklerden',
    'siklere',
    'sikleri',
    'siklerin',
    'sikmek',
    'sikmemek',
    'sikte',
    'sikten',
    'siktir',
    'siktirir siktirmez',
    'taşağa',
    'taşağı',
    'taşağın',
    'taşak',
    'taşaklar',
    'taşaklara',
    'taşaklarda',
    'taşaklardan',
    'taşakları',
    'taşakların',
    'taşakta',
    'taşaktan',
    'yarağa',
    'yarağı',
    'yarağın',
    'yarak',
    'yaraklar',
    'yaraklara',
    'yaraklarda',
    'yaraklardan',
    'yarakları',
    'yarakların',
    'yarakta',
    'yaraktan',
    '13点',
    '三级片',
    '下三烂',
    '下贱',
    '个老子的',
    '九游',
    '乳',
    '乳交',
    '乳头',
    '乳房',
    '乳波臀浪',
    '交配',
    '仆街',
    '他奶奶',
    '他奶奶的',
    '他奶娘的',
    '他妈',
    '他妈ㄉ王八蛋',
    '他妈地',
    '他妈的',
    '他娘',
    '他马的',
    '你个傻比',
    '你他马的',
    '你全家',
    '你奶奶的',
    '你她马的',
    '你妈',
    '你妈的',
    '你娘',
    '你娘卡好',
    '你娘咧',
    '你它妈的',
    '你它马的',
    '你是鸡',
    '你是鸭',
    '你马的',
    '做爱',
    '傻比',
    '傻逼',
    '册那',
    '军妓',
    '几八',
    '几叭',
    '几巴',
    '几芭',
    '刚度',
    '刚瘪三',
    '包皮',
    '十三点',
    '卖B',
    '卖比',
    '卖淫',
    '卵',
    '卵子',
    '双峰微颤',
    '口交',
    '口肯',
    '叫床',
    '吃屎',
    '后庭',
    '吹箫',
    '塞你公',
    '塞你娘',
    '塞你母',
    '塞你爸',
    '塞你老师',
    '塞你老母',
    '处女',
    '外阴',
    '大卵子',
    '大卵泡',
    '大鸡巴',
    '奶',
    '奶奶的熊',
    '奶子',
    '奸',
    '奸你',
    '她妈地',
    '她妈的',
    '她马的',
    '妈B',
    '妈个B',
    '妈个比',
    '妈个老比',
    '妈妈的',
    '妈比',
    '妈的',
    '妈的B',
    '妈逼',
    '妓',
    '妓女',
    '妓院',
    '妳她妈的',
    '妳妈的',
    '妳娘的',
    '妳老母的',
    '妳马的',
    '姘头',
    '姣西',
    '姦',
    '娘个比',
    '娘的',
    '婊子',
    '婊子养的',
    '嫖娼',
    '嫖客',
    '它妈地',
    '它妈的',
    '密洞',
    '射你',
    '射精',
    '小乳头',
    '小卵子',
    '小卵泡',
    '小瘪三',
    '小肉粒',
    '小骚比',
    '小骚货',
    '小鸡巴',
    '小鸡鸡',
    '屁眼',
    '屁股',
    '屄',
    '屌',
    '巨乳',
    '干x娘',
    '干七八',
    '干你',
    '干你妈',
    '干你娘',
    '干你老母',
    '干你良',
    '干妳妈',
    '干妳娘',
    '干妳老母',
    '干妳马',
    '干您娘',
    '干机掰',
    '干死CS',
    '干死GM',
    '干死你',
    '干死客服',
    '幹',
    '强奸',
    '强奸你',
    '性',
    '性交',
    '性器',
    '性无能',
    '性爱',
    '情色',
    '想上你',
    '懆您妈',
    '懆您娘',
    '懒8',
    '懒八',
    '懒叫',
    '懒教',
    '成人',
    '我操你祖宗十八代',
    '扒光',
    '打炮',
    '打飞机',
    '抽插',
    '招妓',
    '插你',
    '插死你',
    '撒尿',
    '操你',
    '操你全家',
    '操你奶奶',
    '操你妈',
    '操你娘',
    '操你祖宗',
    '操你老妈',
    '操你老母',
    '操妳',
    '操妳全家',
    '操妳妈',
    '操妳娘',
    '操妳祖宗',
    '操机掰',
    '操比',
    '操逼',
    '放荡',
    '日他娘',
    '日你',
    '日你妈',
    '日你老娘',
    '日你老母',
    '日批',
    '月经',
    '机八',
    '机巴',
    '机机歪歪',
    '杂种',
    '浪叫',
    '淫',
    '淫乱',
    '淫妇',
    '淫棍',
    '淫水',
    '淫秽',
    '淫荡',
    '淫西',
    '湿透的内裤',
    '激情',
    '灨你娘',
    '烂货',
    '烂逼',
    '爛',
    '狗屁',
    '狗日',
    '狗狼养的',
    '玉杵',
    '王八蛋',
    '瓜娃子',
    '瓜婆娘',
    '瓜批',
    '瘪三',
    '白烂',
    '白痴',
    '白癡',
    '祖宗',
    '私服',
    '笨蛋',
    '精子',
    '老二',
    '老味',
    '老母',
    '老瘪三',
    '老骚比',
    '老骚货',
    '肉壁',
    '肉棍子',
    '肉棒',
    '肉缝',
    '肏',
    '肛交',
    '肥西',
    '色情',
    '花柳',
    '荡妇',
    '賤',
    '贝肉',
    '贱B',
    '贱人',
    '贱货',
    '贼你妈',
    '赛你老母',
    '赛妳阿母',
    '赣您娘',
    '轮奸',
    '迷药',
    '逼',
    '逼样',
    '野鸡',
    '阳具',
    '阳萎',
    '阴唇',
    '阴户',
    '阴核',
    '阴毛',
    '阴茎',
    '阴道',
    '阴部',
    '雞巴',
    '靠北',
    '靠母',
    '靠爸',
    '靠背',
    '靠腰',
    '驶你公',
    '驶你娘',
    '驶你母',
    '驶你爸',
    '驶你老师',
    '驶你老母',
    '骚比',
    '骚货',
    '骚逼',
    '鬼公',
    '鸡8',
    '鸡八',
    '鸡叭',
    '鸡吧',
    '鸡奸',
    '鸡巴',
    '鸡芭',
    '鸡鸡',
    '龟儿子',
    '龟头',
    '𨳒',
    '陰莖',
    '㞗',
    '尻',
    '𨳊',
    '鳩',
    '𡳞',
    '𨶙',
    '撚',
    '𨳍',
    '柒',
    '閪',
    '咸家鏟',
    '冚家鏟',
    '咸家伶',
    '冚家拎',
    '笨實',
    '粉腸',
    '屎忽',
    '躝癱',
    '你老闆',
    '你老味',
    '你老母',
    '硬膠',
    // Add more words or phrases as needed
  ];

  // Define a regular expression pattern to match the inappropriate words
  const pattern = new RegExp('\\b(' + inappropriateWords.join('|') + ')\\b', 'gi');

  // Get a reference to the text area element
  const textArea = document.getElementById('sensor');

  // Add an event listener to the text area to filter the input
  textArea.addEventListener('keyup', function(event) {
    // Get the current value of the text area
    const text = event.target.value;

    // Replace any inappropriate words with asterisks
    const filteredText = text.replace(pattern, '***');

    // Update the text area with the filtered text
    event.target.value = filteredText;

    // Check if the filtered text is different from the original text
    if (filteredText !== text) {
      // Show an alert message in the browser
      alert('Inappropriate content detected. Please remove it.');

      // Set the focus to the text area
      event.target.focus();
    }
  });