name: Generate Earthquake News

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install github

      - name: Generate news article
        env:
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB: ${{ secrets.GITHUB }}
        run: python news.py
